"""Friendly built-in effects expressed in the public EffectSpec format."""

from __future__ import annotations

from typing import Any


def color(hue: float, saturation: float, brightness: float) -> dict[str, float]:
    return {"hue": hue, "saturation": saturation, "brightness": brightness}


PRESETS: dict[str, dict[str, Any]] = {
    "aurora": {
        "schema_version": 2,
        "id": "aurora",
        "name": "Aurora",
        "description": "Soft green and violet ribbons drifting up the Tube.",
        "speed": 0.62,
        "background": color(205, 0.72, 0.10),
        "layers": [
            {
                "type": "wave",
                "axis": "y",
                "color": color(142, 0.88, 0.48),
                "frequency": 1.1,
                "speed": 0.7,
                "intensity": 0.62,
                "seed": 3,
            },
            {
                "type": "ribbon",
                "axis": "diagonal",
                "color": color(294, 0.68, 0.62),
                "frequency": 1.7,
                "speed": -0.48,
                "phase": 0.3,
                "intensity": 0.52,
                "seed": 5,
            },
        ],
    },
    "ocean": {
        "schema_version": 2,
        "id": "ocean",
        "name": "Ocean Current",
        "description": "Deep blue water crossed by slow turquoise currents.",
        "speed": 0.52,
        "background": color(224, 0.9, 0.09),
        "layers": [
            {
                "type": "wave",
                "axis": "diagonal",
                "color": color(184, 0.88, 0.62),
                "frequency": 1.3,
                "speed": 0.55,
                "intensity": 0.72,
                "seed": 14,
            },
            {
                "type": "ribbon",
                "axis": "y",
                "color": color(202, 0.45, 0.72),
                "frequency": 2.1,
                "speed": -0.28,
                "intensity": 0.34,
                "seed": 15,
            },
        ],
    },
    "embers": {
        "schema_version": 2,
        "id": "embers",
        "name": "Campfire Embers",
        "description": "Warm orange currents with tiny rising sparks.",
        "speed": 0.85,
        "background": color(4, 0.96, 0.08),
        "layers": [
            {
                "type": "wave",
                "axis": "y",
                "color": color(28, 0.98, 0.57),
                "frequency": 1.6,
                "speed": -0.7,
                "intensity": 0.7,
                "seed": 21,
            },
            {
                "type": "sparkles",
                "color": color(52, 0.54, 0.95),
                "count": 8,
                "speed": 1.0,
                "drift": -0.5,
                "intensity": 0.88,
                "seed": 22,
            },
        ],
    },
    "candy": {
        "schema_version": 2,
        "id": "candy",
        "name": "Candy Twist",
        "description": "Cheerful pink and aqua bands winding around one another.",
        "speed": 0.78,
        "background": color(325, 0.75, 0.12),
        "layers": [
            {
                "type": "ribbon",
                "axis": "diagonal",
                "color": color(334, 0.88, 0.74),
                "frequency": 1.35,
                "speed": 0.72,
                "intensity": 0.82,
                "seed": 31,
            },
            {
                "type": "ribbon",
                "axis": "diagonal",
                "color": color(176, 0.82, 0.76),
                "frequency": 1.35,
                "speed": 0.72,
                "phase": 0.5,
                "intensity": 0.74,
                "seed": 32,
            },
        ],
    },
    "fireflies": {
        "schema_version": 2,
        "id": "fireflies",
        "name": "Fireflies",
        "description": "Small golden lights blinking in a dark green garden.",
        "speed": 0.7,
        "background": color(130, 0.8, 0.055),
        "layers": [
            {
                "type": "wave",
                "axis": "y",
                "color": color(112, 0.7, 0.13),
                "frequency": 0.8,
                "speed": 0.2,
                "intensity": 0.4,
                "seed": 41,
            },
            {
                "type": "sparkles",
                "color": color(55, 0.48, 1.0),
                "count": 10,
                "speed": 1.0,
                "drift": 0.22,
                "intensity": 1.0,
                "seed": 42,
            },
        ],
    },
    "rainbow_parade": {
        "schema_version": 2,
        "id": "rainbow_parade",
        "name": "Rainbow Parade",
        "description": "Broad colour-changing bands marching along the Tube.",
        "speed": 0.9,
        "background": color(265, 0.88, 0.09),
        "layers": [
            {
                "type": "gradient",
                "axis": "y",
                "color": color(345, 0.9, 0.62),
                "palette": [
                    color(345, 0.9, 0.62),
                    color(42, 0.9, 0.72),
                    color(128, 0.82, 0.64),
                    color(190, 0.84, 0.7),
                    color(265, 0.82, 0.66),
                    color(345, 0.9, 0.62),
                ],
                "speed": 0.65,
                "phase": 0,
                "intensity": 0.72,
                "hue_motion": {
                    "mode": "rotate",
                    "amplitude": 0,
                    "speed": 0.7,
                    "phase": 0,
                },
                "seed": 51,
            },
            {
                "type": "chase",
                "axis": "y",
                "color": color(52, 0.7, 0.88),
                "frequency": 2,
                "width": 0.32,
                "speed": 0.82,
                "intensity": 0.5,
                "hue_motion": {
                    "mode": "rotate",
                    "amplitude": 0,
                    "speed": 0.9,
                    "phase": 0,
                },
                "seed": 52,
            },
        ],
    },
    "moon_breath": {
        "schema_version": 2,
        "id": "moon_breath",
        "name": "Moon Breath",
        "description": "A calm blue-white glow that slowly breathes brighter and dimmer.",
        "speed": 0.42,
        "background": color(222, 0.6, 0.08),
        "layers": [
            {
                "type": "gradient",
                "axis": "y",
                "color": color(197, 0.38, 0.42),
                "speed": -0.2,
                "phase": 0.2,
                "intensity": 0.52,
                "seed": 61,
            },
            {
                "type": "pulse",
                "color": color(215, 0.16, 0.66),
                "frequency": 0.65,
                "speed": 0.55,
                "intensity": 0.72,
                "seed": 62,
            },
        ],
    },
    "sonar": {
        "schema_version": 2,
        "id": "sonar",
        "name": "Sonar",
        "description": "Bright turquoise rings travel through deep ocean blue.",
        "speed": 0.72,
        "background": color(225, 0.94, 0.06),
        "layers": [
            {
                "type": "ripple",
                "color": color(174, 0.78, 0.84),
                "frequency": 2.1,
                "center_x": 0.5,
                "center_y": 0.5,
                "speed": 0.75,
                "intensity": 0.9,
                "seed": 71,
            },
            {
                "type": "pulse",
                "color": color(198, 0.52, 0.34),
                "frequency": 1,
                "speed": 0.4,
                "phase": 0.5,
                "intensity": 0.3,
                "seed": 72,
            },
        ],
    },
    "comet_chase": {
        "schema_version": 2,
        "id": "comet_chase",
        "name": "Comet Chase",
        "description": "Two luminous comets chase one another through violet space.",
        "speed": 1.05,
        "background": color(265, 0.9, 0.055),
        "layers": [
            {
                "type": "chase",
                "axis": "y",
                "color": color(188, 0.66, 0.92),
                "frequency": 2,
                "width": 0.28,
                "speed": 0.9,
                "intensity": 0.92,
                "seed": 81,
            },
            {
                "type": "sparkles",
                "color": color(318, 0.62, 0.86),
                "count": 6,
                "drift": -0.18,
                "speed": 0.8,
                "intensity": 0.58,
                "seed": 82,
            },
        ],
    },
    "storybook_sky": {
        "schema_version": 2,
        "id": "storybook_sky",
        "name": "Storybook Sky",
        "description": "Sunrise becomes a bright day, then melts into a starry night.",
        "speed": 0.72,
        "duration": 7,
        "transition": 2,
        "background": color(326, 0.66, 0.10),
        "layers": [
            {
                "type": "gradient",
                "axis": "y",
                "color": color(24, 0.82, 0.7),
                "palette": [
                    color(302, 0.62, 0.4),
                    color(8, 0.82, 0.66),
                    color(48, 0.72, 0.88),
                ],
                "speed": 0.12,
                "intensity": 0.9,
                "seed": 91,
            }
        ],
        "scenes": [
            {
                "name": "Blue day",
                "duration": 7,
                "transition": 2,
                "background": color(210, 0.62, 0.16),
                "layers": [
                    {
                        "type": "gradient",
                        "axis": "y",
                        "color": color(188, 0.42, 0.68),
                        "palette": [
                            color(218, 0.72, 0.46),
                            color(190, 0.5, 0.72),
                            color(52, 0.18, 0.9),
                        ],
                        "speed": -0.08,
                        "intensity": 0.82,
                        "seed": 92,
                    }
                ],
            },
            {
                "name": "Starry night",
                "duration": 8,
                "transition": 2.5,
                "background": color(248, 0.88, 0.045),
                "layers": [
                    {
                        "type": "gradient",
                        "axis": "y",
                        "color": color(276, 0.7, 0.34),
                        "palette": [
                            color(238, 0.82, 0.18),
                            color(274, 0.74, 0.36),
                            color(316, 0.62, 0.28),
                        ],
                        "speed": 0.08,
                        "intensity": 0.58,
                        "seed": 93,
                    },
                    {
                        "type": "sparkles",
                        "color": color(52, 0.2, 1),
                        "count": 9,
                        "speed": 0.72,
                        "drift": 0.08,
                        "intensity": 0.92,
                        "seed": 94,
                    },
                ],
            },
        ],
    },
    "party_chapters": {
        "schema_version": 2,
        "id": "party_chapters",
        "name": "Party Chapters",
        "description": "Candy stripes, a rainbow chase, then a glittering finale.",
        "speed": 1,
        "duration": 5,
        "transition": 1.25,
        "background": color(320, 0.86, 0.08),
        "layers": [
            {
                "type": "gradient",
                "axis": "diagonal",
                "color": color(330, 0.88, 0.7),
                "palette": [
                    color(330, 0.88, 0.7),
                    color(178, 0.78, 0.72),
                    color(48, 0.76, 0.78),
                    color(330, 0.88, 0.7),
                ],
                "speed": 0.55,
                "intensity": 0.86,
                "seed": 101,
            }
        ],
        "scenes": [
            {
                "name": "Rainbow chase",
                "duration": 5,
                "transition": 1.25,
                "background": color(260, 0.9, 0.06),
                "layers": [
                    {
                        "type": "chase",
                        "axis": "y",
                        "color": color(20, 0.88, 0.9),
                        "palette": [
                            color(8, 0.9, 0.86),
                            color(54, 0.82, 0.9),
                            color(150, 0.82, 0.82),
                            color(220, 0.8, 0.86),
                            color(310, 0.82, 0.86),
                        ],
                        "frequency": 2,
                        "width": 0.34,
                        "speed": 1,
                        "intensity": 0.96,
                        "seed": 102,
                    }
                ],
            },
            {
                "name": "Glitter finale",
                "duration": 5,
                "transition": 1.25,
                "background": color(282, 0.86, 0.08),
                "layers": [
                    {
                        "type": "pulse",
                        "color": color(315, 0.72, 0.56),
                        "palette": [
                            color(315, 0.72, 0.56),
                            color(182, 0.68, 0.7),
                            color(48, 0.58, 0.84),
                        ],
                        "frequency": 1.2,
                        "speed": 0.8,
                        "intensity": 0.62,
                        "seed": 103,
                    },
                    {
                        "type": "sparkles",
                        "color": color(50, 0.3, 1),
                        "palette": [
                            color(50, 0.3, 1),
                            color(185, 0.48, 0.92),
                            color(330, 0.5, 0.96),
                        ],
                        "count": 12,
                        "drift": 0.26,
                        "speed": 1,
                        "intensity": 1,
                        "seed": 104,
                    },
                ],
            },
        ],
    },
}
